Extend MsappArchive APIs
microsoft/PowerApps-Tooling pull request #675
Opened 2024-06-21 05:02 UTC by joem-msft

This PR moves some new APIs used in the DocSvr code into the MsappArchive and IMsappArchive APIs in this repo.
- `DoesEntryExist` - allows callers to determine whether an entry exists w/o needing to inspect internal canonical dictionary.
- `TryGenerateUniqueEntryPath` - exposes logic for generating a unique entry, in case similar entries already exist. This function is similar to the private method `GetSafeEntryPath`, but this method only has a single responsibility, in order to make it more usable for different scenarios.
- `MsappArchive.TryMakeSafeForEntryPathSegment` is a new static method that has a single responsibility, allowing it's usage to be composed with other functions  depending on the scenario. It is similar to encoding a path segment of a URI. Namely, the char set it allows is anything that could be a valid file name or directory name.
- `GetSafeEntryPath` is modified to use the new `TryGenerateUniqueEntryPath` and `TryMakeSafeForEntryPathSegment` methods.
- The `GetEntry`, `GetRequiredEntry` methods were updated to utilize the `TryGetEntry` method.

Validation:
- Added additional unit tests for the three new methods
- Updated existing test output due to '.' chars now being a valid file/directory name.

2024-06-21 13:12 UTC, mizrael reviewed
do we really need to add these methods to the interface? can't we have them exposed as extension methods instead?

2024-06-21 14:34 UTC, petrochuk requested changes

2024-06-21 14:34 UTC, petrochuk commented on src/Persistence.Tests/MsApp/MsappArchiveSaveTests.cs
> +    [DataRow(@"..\..\Hello", $"src/....Hello.pa.yaml", @"_TestData/ValidYaml-CI/Screen-Hello2.pa.yaml")]
Can we keep existing test cases and add new ones instead?

2024-06-21 14:34 UTC, petrochuk commented on src/Persistence.Tests/MsApp/MsappArchiveTests.cs
> +using Moq;
It is not recommended to use Moq because of serious privacy concerns: https://github.com/devlooped/moq/issues/1372

2024-06-21 14:34 UTC, petrochuk commented on src/Persistence/MsApp/MsappArchive.cs
> +        if (!DoesEntryExist(entryPath))
This checks raw path against canonical entries which can be an issue if path is "/entryA" for example

2024-06-24 23:01 UTC, tehcrashxor approved these changes

2024-06-25 17:50 UTC, tehcrashxor approved these changes

2024-06-25 18:03 UTC, swapnilbhalgat approved these changes

2024-06-25 18:03 UTC, merged