prevent 'error IDE0036: Modifiers are not ordered'
microsoft/PowerApps-Tooling pull request #710
Opened 2024-08-21 19:00 UTC by jburnett

Using `build ci` at githash 5b4aa54 gives 'error IDE0036: Modifiers are not ordered'

/Users/jb/src/github.com/microsoft/PowerApps-Tooling/src/Persistence/Collections/ControlPropertiesCollection.cs(10,5): error IDE0036: Modifiers are not ordered (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0036) [/Users/jb/src/github.com/microsoft/PowerApps-Tooling/src/Persistence/Microsoft.PowerPlatform.PowerApps.Persistence.csproj] /Users/jb/src/github.com/microsoft/PowerApps-Tooling/src/Persistence/Collections/CustomPropertiesCollection.cs(10,5): error IDE0036: Modifiers are not ordered (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0036) [/Users/jb/src/github.com/microsoft/PowerApps-Tooling/src/Persistence/Microsoft.PowerPlatform.PowerApps.Persistence.csproj] /Users/jb/src/github.com/microsoft/PowerApps-Tooling/src/Persistence/Collections/CustomPropertyParametersCollection.cs(10,5): error IDE0036: Modifiers are not ordered (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0036) [/Users/jb/src/github.com/microsoft/PowerApps-Tooling/src/Persistence/Microsoft.PowerPlatform.PowerApps.Persistence.csproj] /Users/jb/src/github.com/microsoft/PowerApps-Tooling/src/Persistence/Extensions/YamlExtensions.cs(11,5): error IDE0036: Modifiers are not ordered (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0036) [/Users/jb/src/github.com/microsoft/PowerApps-Tooling/src/Persistence/Microsoft.PowerPlatform.PowerApps.Persistence.csproj] /Users/jb/src/github.com/microsoft/PowerApps-Tooling/src/Persistence/PaYaml/Models/NamedObjectMapping.cs(16,5): error IDE0036: Modifiers are not ordered (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0036) [/Users/jb/src/github.com/microsoft/PowerApps-Tooling/src/Persistence/Microsoft.PowerPlatform.PowerApps.Persistence.csproj] /Users/jb/src/github.com/microsoft/PowerApps-Tooling/src/Persistence/PaYaml/Models/NamedObjectSequence.cs(12,5): error IDE0036: Modifiers are not ordered (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0036) [/Users/jb/src/github.com/microsoft/PowerApps-Tooling/src/Persistence/Microsoft.PowerPlatform.PowerApps.Persistence.csproj]
    0 Warning(s)
    6 Error(s)

If this is related to an issue open in GitHub, please link it to this ticket and put the URL here.

## Problem

What is the issue we are attempting to solve?

## Solution

What are we doing to solve this issue?

## Changes

- Log what was changed
- Log what was changed
- Log what was changed

## Validation

- How did you verify that this issue is truly fixed?

2024-08-21 19:11 UTC, tehcrashxor requested changes
Looks like the style diagnostic is complaining about occurrences of `readonly static` which should be `static readonly`.   A better fix would be updating those instances instead of turning off the diagnostic.

2024-08-23 20:07 UTC, jburnett commented
@microsoft-github-policy-service agree

2024-08-23 20:08 UTC, jburnett commented
I resubmitted with changes to field decorator order as suggested.

2024-08-23 22:27 UTC, joem-msft approved these changes

2024-08-23 22:29 UTC, tehcrashxor approved these changes

2024-08-28 01:51 UTC, merged